
logging:
  level:
    org.springframework.web: WARN
    com.datastax.astra: INFO
    com.datastax.rag: INFO
    root: WARN

astra:
  database:
    name: langchain4j
    keyspace: langchain4j
    table: langchain4j
  api:
    # Astra Credentials it stars with AstraCS:..
    application-token: ${ASTRA_DB_APPLICATION_TOKEN}
    # Database UUID
    database-id: ${ASTRA_DB_ID}
    # Database Region (eg: us-east1) no need to specify a cloud name
    database-region: ${ASTRA_DB_REGION}
    # cross-region-failback: false
  cql:
    # Connecting with a regular CqlSession
    enabled: true
    # Download the Secure Connect Bundle, zip file containing the certificates to open the mTLS connection.
    download-scb:
      enabled: true
      # customize local path to download the SCB
      # path: /tmp

    # Full fledged driver configuration
    # see https://docs.datastax.com/en/developer/java-driver/latest/manual/core/configuration/
    driver-config:
      basic:
        session-keyspace: ${ASTRA_DB_KEYSPACE:langchain4j}

openai:
  embeddings-model: text-embedding-ada-002
  chat-completion-model: gpt-3.5-turbo
  
generative-ai:
  table-name: philosophers
  llm-model:
    dimension: 1536
    embeddings: text-embedding-ada-002
    chat-completion: gpt-3.5-turbo

